version: '3'

services:
  app:
    build: .
    image: gfg/flask-app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:4.0.11-alpine
